---
# tasks file for user
- name: USER | Managing users...
  become: true
  ansible.builtin.user:
    comment: '{{ item.comment | default(omit) }}'
    create_home: '{{ item.create_home | default(omit) }}'
    expires: '{{ item.expires | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    home: '{{ item.home | default(omit) }}'
    local: '{{ item.local | default(omit) }}'
    move_home: '{{ item.move_home | default(omit) }}'
    name: '{{ item.name }}'
    non_unique: '{{ item.non_unique | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    state: '{{ item.state | default(user__default_state) }}'
    system: '{{ item.system | default(omit) }}'
    uid: '{{ item.uid | default(omit) }}'
    umask: '{{ item.umask | default(omit) }}'
    update_password: '{{ item.update_password | default(omit) }}'
  with_items: '{{ user }}'
  when: user is defined
  tags:
    - user
    - manage

- name: USER | Manage authorized_key file...
  become: true
  ansible.posix.authorized_key:
    comment: '{{ item.authorized_key.comment | default(omit) }}'
    exclusive: '{{item.authorized_key.exclusive | default(omit) }}'
    follow: '{{ item.authorized_key.follow | default(omit) }}'
    key: '{{ item.authorized_key.key }}'
    key_options: '{{ item.authorized_key.key_options | default(omit) }}'
    manage_dir: '{{ item.authorized_key.manage_dir | default(omit) }}'
    path: '{{ item.authorized_key.path | default(omit) }}'
    state: '{{ item.authorized_key.state | default(user__default_authorized_key_state) }}'
    user: '{{ item.name }}'
    validate_cert: '{{ item.authorized_key.validate_cert | default(omit) }}'
  with_items: '{{ item.authorized_key }}'
  loop: '{{ user }}'
  when: item.authorized_key is defined
  tags:
    - authorized_key
    - manage
