---
# tasks file for user
- name: USER | Managing users...
  become: true
  ansible.builtin.user:
    comment: '{{ item.comment | default(omit) }}'
    create_home: '{{ item.create_home | default(omit) }}'
    expires: '{{ item.expires | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    groups: '{{ item.groups | default(omit) }}'
    home: '{{ item.home | default(omit) }}'
    local: '{{ item.local | default(omit) }}'
    move_home: '{{ item.move_home | default(omit) }}'
    name: '{{ item.name }}'
    non_unique: '{{ item.non_unique | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    state: '{{ item.state | default(user__default_state) }}'
    system: '{{ item.system | default(omit) }}'
    uid: '{{ item.uid | default(omit) }}'
    umask: '{{ item.umask | default(omit) }}'
    update_password: '{{ item.update_password | default(omit) }}'
  with_items: '{{ user_user }}'
  when: user_user is defined
  tags:
    - user_user
    - manage

