---
# tasks file for user
- name: USER | Managing users...
  ansible.builtin.user:
    comment: {{ item.comment | default("") }}
    create_home: {{ item.create_home | default("true") }}
    expires: {{ item.expires | default("-1") }}
    force: {{ item.force | default("false") }}
    group: {{ item.group | default("{{ item }}") }}
    groups: {{ item.groups | default("") }}
    home: {{ item.home | default("/home/{{ item }}") }}
    local: {{ item.local | default("false") }}
    move_home: {{ item.move_home | default("false") }}
    name: {{ item }}
    non_unique: {{ item.non_unique | default("false") }}
    password: {{ item.password | default("!") }}
    remove: {{ item.remove | default("false") }}
    shell: {{ item.shell | default("/bin/sh") }}
    state: {{ item.state | default("present") }}
    system: {{ item.system | default("false") }}
    uid: {{ item.uid | default("") }}
    umask: {{ item.umask | default("022") }}
    update_password: {{ item.update_password | default("always") }}
  with_items: '{{ user }}'
  tags: [ manage ]

